Closes #709
raml-org/raml-spec pull request #734
Opened 2020-08-17 18:20 UTC by jstoiko

2020-12-18 22:42 UTC, priyaayyar requested changes

2020-12-18 22:42 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
```suggestion
It is highly recommended that the API documentation includes a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declaration. In addition to YAML(default), processors must support JSON and XML examples. Processors may support additional formats. Note that the type definition is agnostic to example encoding such that the examples in YAML work for JSON or XML, and in reverse for any chosen combination of those three supported encodings.
```

2020-12-18 22:42 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +| strict? | Validates the example against any type declaration (the default). Set this to false to prevent validation.
```suggestion
| strict? | Validates the example against any type declaration (default). Set this to false to prevent validation.
```

2020-12-18 23:33 UTC, dukesphere requested changes

2020-12-18 23:33 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
Question, please clarify: What is mean by "and in reverse"? I think it probably means that you can write the example in any of the three formats will work for the others, but I'm not 100% sure if that's correct. Can you clarify that? I did not attempt to modify that part of the paragraph.

```suggestion
It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declaration. In addition to supporting YAML by default, processors SHOULD support JSON and XML representations of examples. Processors MAY support additional formats. Note that type definition is agnostic to example encoding; for example, examples in YAML will work for JSON or XML, and in reverse for any chosen combination of those three supported encodings.
```

2020-12-24 02:47 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
I think it means "vice versa".

2020-12-24 03:10 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
```suggestion
It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declaration. In addition to YAML by default, processors SHOULD support JSON and XML representations of examples. Processors MAY support additional formats. Note that type definition is agnostic to example encoding; for example, examples in YAML will work for JSON or XML, and in reverse for any chosen combination of those three supported encodings.
```

2020-12-29 18:46 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
```suggestion
It is highly RECOMMENDED that the API documentation includes a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declaration. In addition to YAML(default), processors SHOULD support JSON and XML representations of examples. Processors MAY support additional formats. Note that type definition is agnostic to example encoding, for example, examples in YAML will work for JSON or XML, and vice versa, for any chosen combination of those three supported encodings.
```

2020-12-29 18:52 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
or you can put it like this:
Ensure that your API documentation includes a rich selection of examples. RAML supports the definition of either multiple examples or a single one for any given instance of a type declaration. In addition to supporting YAML by default, processors SHOULD support JSON and XML representations of examples, and OPTIONALLY support additional formats. Note that type definition is agnostic to example encoding; examples in any of YAML, JSON, or XML also work for the other two.

2020-12-29 19:54 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
I think I prefer `In addition to supporting YAML by default`. 

Regarding the last sentence I prefer the: 

> Note that type definition is agnostic to example encoding, for example, examples in YAML will work for JSON or XML, and vice versa, for any chosen combination of those three supported encodings.

form, although I am not sure we need the `, for example,` part. Can we say: 

> Note that type definition is agnostic to example encoding: examples in YAML will work for JSON or XML, and vice versa, for any chosen combination of those three supported encodings.

instead?

2020-12-30 02:41 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +It is highly RECOMMENDED that API documentation include a rich selection of examples. RAML supports either the definition of multiple examples or a single one for any given instance of a type declara
sure

2020-12-30 02:41 UTC, priyaayyar approved these changes

2021-01-09 06:20 UTC, dukesphere approved these changes

2021-04-09 22:18 UTC, merged