Closes #710
raml-org/raml-spec pull request #735
Opened 2020-08-17 18:20 UTC by jstoiko

2020-12-18 22:36 UTC, priyaayyar requested changes

2020-12-18 22:36 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +* If, and only if, a type declaration contains a facet that is unique to that type, then its default type is inferred to be the only one with support for the facet being used.
```suggestion
* If, and only if, a type declaration contains a facet that is unique to that type, its default type is then inferred to be the only one with support for the facet being used.
```

2020-12-18 22:36 UTC, priyaayyar commented on versions/raml-10/raml-10.md
>  ```yaml
Put the code in a code tag?

2020-12-18 22:36 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +* If, and only if, a type declaration contains neither a facet that is unique to a given type as described in the previous rule above, nor a `type` or `schema` facet, then the default type is `string
```suggestion
* If, and only if, a type declaration contains a facet that is neither unique to a given type, as described in the previous rule above, nor a `type` or `schema` facet, then the default type is `string`. The following snippet exemplifies this rule:
```

2020-12-18 22:36 UTC, priyaayyar commented on versions/raml-10/raml-10.md
>  ```yaml
Put the code in a code tag?

2020-12-24 02:43 UTC, jstoiko commented on versions/raml-10/raml-10.md
>  ```yaml
That's the case, i.e. that's what those 3 backticks do...

2020-12-24 03:08 UTC, dukesphere approved these changes

2020-12-30 02:40 UTC, priyaayyar approved these changes

2021-04-09 22:19 UTC, merged