Closes #711
raml-org/raml-spec pull request #736
Opened 2020-08-17 18:20 UTC by jstoiko

2020-09-03 18:27 UTC, BlockLucas commented
Hi!

Unions didn’t have facets in 1.0.
For us is not a PATCH change as an API with the following cases (defined in this PR), would be invalid in RAML 1.0:

```yaml
types:
  Foo: number
  Bar: integer
  Qux:
    type: string
    facets:
      minimum: number
  FooBarQux:
    type: Foo | Bar | Qux
    minimum: 1 # valid because "Qux" (string) has a user-defined facet "minimum"
```

```yaml
types:
  Foo: number
  Bar: integer
  FooBar:
    type: Foo | Bar
    minimum: 1 # valid because both "Foo" (number) and "Bar" (integer) all accept "minimum"
```

2020-09-05 00:39 UTC, jstoiko commented
Where do you see that the union type cannot have [facets](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md)?

2020-12-18 22:30 UTC, priyaayyar requested changes

2020-12-18 22:30 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +A union type MAY use facets defined by any of its member types as long as all member types in the union accept those facets.
```suggestion
A `union` type may use facets defined by any of its member types, as long as all member types in the union accept those facets, for example:
```

2020-12-18 22:30 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +For example:
```suggestion
For example: (delete)
```

2020-12-18 22:30 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +```yaml
Add the whole example in a code tag, like this:
[source, text, linenums]
----
Place the whole example here.
----

2020-12-18 22:30 UTC, priyaayyar commented on versions/raml-10/raml-10.md
>  RAML allows the use of XML and JSON schemas to describe the body of an API request or response by integrating the schemas into its data type system.
```suggestion
RAML allows you to use XML and JSON schemas to describe the body of an API request or response by integrating the schemas into its data type system.
```

2020-12-24 03:07 UTC, dukesphere commented on versions/raml-10/raml-10.md
>  RAML allows the use of XML and JSON schemas to describe the body of an API request or response by integrating the schemas into its data type system.
I'd decline the suggested change and keep the original as-is. This and a number of other changes are applying our doc style guidelines but would be inconsistent with the style of the existing doc. So I think our copyedits should be minimal.

2020-12-24 03:07 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +A union type MAY use facets defined by any of its member types as long as all member types in the union accept those facets.
```suggestion
A union type MAY use facets defined by any of its member types as long as all member types in the union accept those facets, for example:
```

2020-12-24 03:07 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +For example:
```suggestion
```

2020-12-24 03:07 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +For example:
use suggested change below, decline above

2020-12-24 03:07 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +```yaml
Priya, this Markdown,  not asciidoc.

2020-12-24 03:07 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +```yaml
@jstoiko Please disregard the suggestion above.

2020-12-29 19:13 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +A union type MAY use facets defined by any of its member types as long as all member types in the union accept those facets.
Tring to make it less wordy. So here is one more attempt:
A union type MAY use facets defined by any of its member types, if the member types in the union accept those facets, for example:

2020-12-30 01:07 UTC, dukesphere approved these changes

2020-12-30 02:40 UTC, priyaayyar approved these changes

2021-04-09 22:19 UTC, merged