Closes #712
raml-org/raml-spec pull request #737
Opened 2020-08-17 18:20 UTC by jstoiko

2020-12-18 22:25 UTC, priyaayyar requested changes

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +If a union type contains a facet with an `enum`, every value of that `enum` MUST meet all restrictions associated with at least one of the super types. Here is an example:
```suggestion
If a union type contains a facet with an `enum`, every value of that `enum` must meet all the restrictions associated with at least one of the super types:
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +This is valid:
```suggestion
The following example illustrates a valid expression:
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +type: number | boolean
```suggestion
`type: number | boolean`
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +enum: [1, true, 2]
```suggestion
`enum: [1, true, 2]`
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +This is invalid:
```suggestion
The following example illustrates an invalid expression:
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +type: number | boolean
```suggestion
`type: number | boolean`
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +enum: [1, true, 2, "hello"]
```suggestion
`enum: [1, true, 2, "hello"]`
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +Recall that types in this case can be built-in data types, such as number or boolean, but also custom user-defined types such as unions or complex types with multiple properties. Imagine a more compl
```suggestion
Note that types, in this case, can be built-in data types, such as numbers or boolean, or can be custom user-defined types, such as unions or complex types with multiple properties. Imagine a more complex example:
```

2020-12-18 22:25 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +
Add the whole example in a code tag, like this:
[source,text,linenums]
----
Add the full example here.
----

2020-12-24 02:38 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +type: number | boolean
the 3 backticks above are meant to format the whole block below it as if each line were surrounded with single backticks so these are not needed.

2020-12-24 02:39 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +enum: [1, true, 2, "hello"]
ditto

2020-12-24 02:41 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +
Not sure to understand. Is the example below not that?

2020-12-30 01:14 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +
There was a misunderstanding. The [source, text, linenums] is not needed in Markdown here. That relates to a convention of our Asciidoc format.

2020-12-30 01:17 UTC, dukesphere approved these changes
I think it's fine as-is.

2020-12-30 02:39 UTC, priyaayyar approved these changes

2021-04-09 22:19 UTC, merged