Closes #716
raml-org/raml-spec pull request #740
Opened 2020-08-17 18:20 UTC by jstoiko

2020-12-18 00:30 UTC, priyaayyar requested changes

2020-12-18 00:30 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +When the base URI ends in one or more slashes (`/`), those trailing slashes are omitted in the absolute paths for the resources using that base URI. For example, in the following snippet, the absolut
```suggestion
When the base URI ends in one or more slashes (`/`), the trailing slashes are omitted in the absolute paths for the resources using that base URI. For example, in the following snippet, the absolute paths for the resources are `http://api.test.com/common/users/:userId` and `http://api.test.com/common/users/:userId/groups`.
```

2020-12-18 00:30 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +Explicitly defining a `mediaType` node for a [body](#bodies) of an API request or response overrides the default media type, as shown in the following example. The resource `/people` returns a `Perso
```suggestion
Explicitly defining a `mediaType` node for a [body](#bodies) of an API request or response overrides the default media type, as shown in the following example. The resource `/people` returns a `Person[]` body in either JSON or XML. The resource `/messages` overrides the default media type by explicitly defining an `application/json` node. Therefore, the resource `/messages` returns only a JSON-formatted body.
```

2020-12-24 03:00 UTC, dukesphere approved these changes

2020-12-30 02:39 UTC, priyaayyar approved these changes

2021-04-09 22:21 UTC, merged