Closes #718
raml-org/raml-spec pull request #741
Opened 2020-08-17 18:20 UTC by jstoiko

2020-09-03 18:20 UTC, BlockLucas commented
Hi! 

Typed fragments didn't specify the usage of “uses” facet, hence the explanation that they MUST be valid according to the relevant RAML specification forbids that.
For us is not a PATCH change as a NamedExample with "uses" as defined in 1.0.1 would be invalid for 1.0

2020-09-04 17:44 UTC, jstoiko commented
@BlockLucas: I think you're putting the finger on the issue that led us to making this clarification (and other clarifications we're including in 1.0.1). Libraries were always meant to be used within any kind of typed fragment. This is what the RAML 1.0 Spec currently says:

> Any number of libraries can be applied by using the OPTIONAL **uses** node ONLY at the root of a master RAML or **RAML fragment file**.
> (...)
> For example, **a RAML type fragment file that uses a library** of remote types can import one of those types by referring to it. The remote type is included as if it were defined locally within the RAML type fragment file.

What we did is we went back to the original discussions that took place prior to the release of the RAML 1.0 spec to understand what the original intent was. And in this case it was pretty obvious that the intent has always been to have libraries be used in any RAML file, whether a RAML API or RAML typed fragment definition. The fact that the "Typed Fragments" section does not have the `uses:` node facet defined currently is an obvious mistake. Fixing this mistake by adding this table doesn't change the fact that these two sentences above were there in the first place.

2020-12-17 23:49 UTC, priyaayyar requested changes

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +Any number of libraries can be applied by using the OPTIONAL **uses** node at the root of a RAML or RAML typed fragment file. The value of the uses node is a map of key-value pairs. The keys are trea
```suggestion
You can apply any number of libraries by using the OPTIONAL `uses` node at the root of a RAML or RAML typed fragment file. The value of the `uses` node is a map of the key-value pairs. The keys are treated as library names, or namespaces, and the value must be the location of a RAML library file, usually an external RAML library fragment document.
```

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +Using **uses** does not automatically import the remote library assets into the local file, but the local file can import those assets by referring to the assets from its contents. For example, a RAM
```suggestion
The `uses` node does not automatically import the remote library assets into the local file. However, the local file can import those assets by referring to the assets from its contents. For example, a RAML typed fragment file that uses a library of remote types can import one of those types by referring to it. The remote type is included as if it were defined locally within the RAML typed fragment file.
```

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +In addition to any nodes allowed in any of the "Relevant RAML Specification Sections" above, the following OPTIONAL node is allowed:
```suggestion
In addition to the nodes allowed in any of the Relevant RAML Specification Sections above, the following optional node is allowed:
```

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +| uses? | Imported external [libraries](#libraries) for use within the RAML typed fragment. |
Is the question mark uses? intentional?

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +If a file begins with a RAML fragment identifier line, and the fragment identifier is not Library, Overlay, or Extension, the contents of the file after removal of the RAML fragment identifier line a
```suggestion
If a file begins with a RAML fragment identifier line, and the fragment identifier is not of type Library, Overlay, or Extension, the contents of the file after removal of the RAML fragment identifier line and any `uses` node must be valid structurally according to the relevant RAML specification. For example, a RAML file beginning with `#%RAML 1.0 Trait` must have the structure of a RAML trait declaration as defined in the [Resource Types and Traits](#resource-types-and-traits) section. Including the file in a correct location for a trait declaration results in a valid RAML file.
```

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +The following example shows a RAML fragment file that defines a resource type and a file that includes this typed fragment file.
```suggestion
The following example shows a RAML fragment file that defines a resource type and a file that includes (this o the?) typed fragment file.
```

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +In addition to any nodes allowed at the root of [RAML typed fragments](#typed-fragments), RAML libraries allow the following optional nodes:
```suggestion
In addition to the nodes allowed at the root of [RAML typed fragments](#typed-fragments), the RAML libraries allow the following optional nodes:
```

2020-12-17 23:49 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +| types?<br>schemas?<br>resourceTypes?<br>traits?<br>securitySchemes?<br>annotationTypes?<br>(&lt;annotationName&gt;)? | The definition of each node is the same as that of the corresponding node at t
```suggestion
| types?<br>schemas?<br>resourceTypes?<br>traits?<br>securitySchemes?<br>annotationTypes?<br>(&lt;annotationName&gt;)? | The definition of each node is the same as that of the corresponding node at the root of a RAML document. A library supports the annotation node like any other RAML document.
```

2020-12-24 02:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +In addition to any nodes allowed in any of the "Relevant RAML Specification Sections" above, the following OPTIONAL node is allowed:
```suggestion
In addition to the nodes allowed in any of the Relevant RAML Specification Sections above, the following OPTIONAL node is allowed:
```

2020-12-24 02:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| uses? | Imported external [libraries](#libraries) for use within the RAML typed fragment. |
it's intentional.

2020-12-24 02:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +If a file begins with a RAML fragment identifier line, and the fragment identifier is not Library, Overlay, or Extension, the contents of the file after removal of the RAML fragment identifier line a
```suggestion
If a file begins with a RAML fragment identifier line, and the fragment identifier is not a Library, Overlay, or Extension, the contents of the file after the removal of the RAML fragment identifier line and any `uses` node MUST be valid structurally according to the relevant RAML specification. For example, a RAML file beginning with `#%RAML 1.0 Trait` must have the structure of a RAML trait declaration as defined in the [Resource Types and Traits](#resource-types-and-traits) section. Including the file in a correct location for a trait declaration results in a valid RAML file.
```

2020-12-24 02:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +The following example shows a RAML fragment file that defines a resource type and a file that includes this typed fragment file.
I'd leave the original paragraph as-is and decline the suggested change.

2020-12-24 02:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +In addition to any nodes allowed at the root of [RAML typed fragments](#typed-fragments), RAML libraries allow the following optional nodes:
Again, I'd leave as-is and decline the suggested change.

2020-12-24 02:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +Any number of libraries can be applied by using the OPTIONAL **uses** node at the root of a RAML or RAML typed fragment file. The value of the uses node is a map of key-value pairs. The keys are trea
```suggestion
You can apply any number of libraries by using the OPTIONAL **uses** node at the root of a RAML or RAML typed fragment file. The value of the **uses** node is a map of key-value pairs. The keys are treated as library names, or namespaces, and the value MUST be the location of a RAML library file, usually an external RAML library fragment document.
```

2020-12-24 02:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +Using **uses** does not automatically import the remote library assets into the local file, but the local file can import those assets by referring to the assets from its contents. For example, a RAM
I'd leave the original as-is and decline the suggested change.

2020-12-29 00:16 UTC, dukesphere approved these changes

2020-12-29 19:46 UTC, priyaayyar approved these changes

2021-04-09 22:22 UTC, merged