Closes #719
raml-org/raml-spec pull request #742
Opened 2020-08-17 18:20 UTC by jstoiko

2020-12-17 20:19 UTC, priyaayyar requested changes

2020-12-17 20:19 UTC, priyaayyar commented on versions/raml-10/raml-10.md
> +The remainder of an overlay or extension document follows the same rules as a RAML API definition, but with certain [restrictions](#overlays) in case of an overlay. The resolution of paths in an over
```suggestion
The remaining overlay or extension document follows the same rules as the RAML API definition, but with certain [restrictions](#overlays) in case of an overlay. The resolution of paths in an overlay or extension document, such as those for `!include` tags or libraries, must be relative to the document from which the reference is being made, as opposed to the API root document.
```

2020-12-19 00:12 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +The remainder of an overlay or extension document follows the same rules as a RAML API definition, but with certain [restrictions](#overlays) in case of an overlay. The resolution of paths in an over
should stay "MUST" not lowercase "must"

2020-12-24 02:40 UTC, dukesphere approved these changes
I don't think the suggested change is necessary. Approving as-is.

2020-12-24 04:53 UTC, dukesphere reviewed
small change, restores MUST, as well

2020-12-24 04:53 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +The remainder of an overlay or extension document follows the same rules as a RAML API definition, but with certain [restrictions](#overlays) in case of an overlay. The resolution of paths in an over
```suggestion
The remainder of an overlay or extension document follows the same rules as a RAML API definition, but with certain [restrictions](#overlays) in case of an overlay. The resolution of paths in an overlay or extension document, such as those for `!include` tags or libraries, MUST be relative to the document from which the reference is made, as opposed to the API root document.
```

2020-12-30 17:36 UTC, priyaayyar approved these changes

2021-04-09 22:22 UTC, merged