Closes #728
raml-org/raml-spec pull request #746
Opened 2020-08-17 18:20 UTC by jstoiko

2020-12-17 18:35 UTC, dukesphere requested changes
is the facet called `format?` or `format`?

2020-12-17 18:35 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +The additional facet `format` MUST be available only when the type equals `datetime`:
```suggestion
The additional facet `format?` MUST be available only when the type equals `datetime`:
```

Not sure if the "?" is required there.

2020-12-24 04:21 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +The additional facet `format` MUST be available only when the type equals `datetime`:
It's not. The name of the facet is "format", the trailing "?" only indicates that it's optional when listed in a table format as it is below, out of this context the "?" is irrelevant.

2020-12-24 04:22 UTC, jstoiko commented
> is the facet called `format?` or `format`?

`format`

2020-12-29 00:48 UTC, dukesphere approved these changes

2021-04-09 22:25 UTC, merged