Misc clarifications
raml-org/raml-spec pull request #748
Opened 2020-08-22 00:08 UTC by jstoiko

### Summary of changes:
- Fixed "Introduction" link in table of contents (closes #725)
- Fixed a minor typo in one of the RAML snippets (https://github.com/raml-org/raml-spec/commit/7e7aa4f3e706c44be75ab673ad805a7731000be0)
- Specify that `!include` cannot be used in type expressions and multiple inheritance (https://github.com/raml-org/raml-spec/commit/35b9df46cf2837c4e5d4a5c3959446765474d267)
- Add missing trailing '?' to the `usage` node definition under Libraries' list of allowed nodes (https://github.com/raml-org/raml-spec/commit/dcb3f7f296e2263700537b56ae5ac8f3721e64d0)
- Removed a confusing sentence above the "Object Type" example (https://github.com/raml-org/raml-spec/commit/5f2fdfa9580b92d14bfc56a863b10834709b1509)
- Fixed typos and minor syntactic corrections (https://github.com/raml-org/raml-spec/commit/c61848974c4d0f89341ec6f3f512a91970da16db)
- Fixed misuse of "JSON Schemas" (files) in the context of "JSON Schema" (the language) (https://github.com/raml-org/raml-spec/commit/f4529873ba3ada1782a72f8ed571184f174276a2)
- Fixed misuse of "XSD" (XML Schema Definition language) in the context of "XML Schema" (https://github.com/raml-org/raml-spec/commit/1873df421cee6262af7f10157894218adc16d004)
- Clarified that the Any type has no ADDITIONAL facets (https://github.com/raml-org/raml-spec/commit/842331b6d5ce51a13f0ff6c38b9770f51deb3a84)
- Clarified description (and examples) of integer and number scalar types (https://github.com/raml-org/raml-spec/commit/8a8fc2e5c8e52694463952d344cf8d354dea3052)
- Clarified the definition of the `additionalProperties` facet of object types (https://github.com/raml-org/raml-spec/commit/d0357be87d8f757f72bdb1396854c7cbdee5446d, https://github.com/raml-org/raml-spec/commit/47d9a6959291d7ec38068c5700eb44ae89b0d30f)
- Fixed typo in 'Resource Type and Trait Parameters (8a45c85, closes #729 and #753)
- Fixed incoherent facet values in String type example (b76d1d0, closes #729)
- Fixed typo 'mixing pattern' to read 'mixin pattern' (29ac49f, closes #753)

2020-12-17 21:51 UTC, dukesphere requested changes
minor tweaks and a couple that were unclear

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +User-defined facets by definition are not built into this RAML specification, and hence their semantic MAY not be understood by all RAML processors. Consequently, a RAML processor may or may not choo
Note: Not sure if MAY needs to be capitalized after "their semantics" or perhaps after "a RAML processor." In the first case, seems that MAY is not a term used for enforcement of the RAML standard, just as a statement of fact that is acknowledged and expected. It's allowed only because it's impossible for the processor to anticipate them. Perhaps the enforcement applies to the processor instead?

```suggestion
By definition, user-defined facets are not built into this RAML specification, and therefore, their semantics might not be understood by all RAML processors. Consequently, a RAML processor MAY (or may not) choose to use user-defined facets on a type in validating instances of that type. In the example above, a RAML processor may or may not assign a meaning to `noHolidays`, and therefore, may choose to ignore the `noHolidays: true` value in validating instances of `PossibleMeetingDate`.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +Type expressions provide a powerful way of referring to, and even defining, types. Type expressions MAY be used wherever a type is expected. The simplest type expression is just the name of a type. U
```suggestion
Type expressions provide a powerful way of referring to, and even defining, types. Type expressions MAY be used wherever a type is expected. The simplest type expression is the name of a type. Using type expressions, you MAY devise type unions, arrays, maps, and other things.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +The user-defined facet is declared using the OPTIONAL `facets` facet in a type declaration. The value of the `facets` facet MUST be a map. The key names the user-defined facet. The corresponding valu
I'd normally recommend "subtype," but "sub-type" is used more often on this page even in unedited areas.

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +If a sub-type inherits properties having the same name from at least two of its parent types, the sub-type SHALL keep all restrictions applied to those properties with two exceptions: 1) a "pattern"
should "pattern" be `pattern` in both places?

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +The OPTIONAL **example** facet MAY be used to attach an example of a type instance to the type declaration. There are two ways to represent the example facet value: as an explicit description of a sp
```suggestion
The OPTIONAL **example** facet MAY be used to attach an example of a type instance to the type declaration. There are two ways to represent the example facet value: as an explicit description of a specific type instance, or as a map that contains additional facets.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| description? | A substantial, human-friendly description for an example. Its value MUST be a string and MAY be formatted using [markdown](#markdown).
```suggestion
| description? | A substantial, human-friendly description for an example. Its value MUST be a string and MAY be formatted using [Markdown](#markdown).
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| (&lt;annotationName&gt;)? | [Annotations](#annotations) to be applied to this API. An annotation MUST be a map having a key that begins with "(" and ends with ")" where the text enclosed in parenth
```suggestion
| (&lt;annotationName&gt;)? | [Annotations](#annotations) to be applied to this API. An annotation MUST be a map having a key that begins with "(" and ends with ")", where the text enclosed in parentheses is the annotation name and the value is an instance of that annotation.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| strict? | Validates the example against any type declaration (the default), or not. Set this to false to avoid validation.
```suggestion
| strict? | Validates the example against any type declaration (the default), or not. Set this facet to false to avoid validation.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +The value of a resource node MUST be a map whose key-value pairs are described in the following table.
```suggestion
The value of a resource node MUST be a map containing the key-value pairs described in the following table.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| description? | A substantial, human-friendly description of a resource. Its value MUST be a string and MAY be formatted using [markdown](#markdown).
```suggestion
| description? | A substantial, human-friendly description of a resource. Its value MUST be a string and MAY be formatted using [Markdown](#markdown).
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| usage? | Describes the content or purpose of a specific library. The value is a string and MAY be formatted using [markdown](#markdown).
```suggestion
| usage? | Describes the content or purpose of a specific library. The value is a string and MAY be formatted using [Markdown](#markdown).
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| (&lt;annotationName&gt;) | [Annotations](#annotations) to be applied to this API. An annotation MUST be a map having a key that begins with "(" and ends with ")" where the text enclosed in parenthe
```suggestion
| (&lt;annotationName&gt;) | [Annotations](#annotations) to be applied to this API. An annotation MUST be a map having a key that begins with "(" and ends with ")", where the text enclosed in parentheses is the annotation name and the value is an instance of that annotation.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| (&lt;annotationName&gt;)? | [Annotations](#annotations) to be applied to this API. An annotation MUST be a map having a key that begins with "(" and ends with ")" where the text enclosed in parenth
```suggestion
| (&lt;annotationName&gt;)? | [Annotations](#annotations) to be applied to this API. An annotation MUST be a map having a key that begins with "(" and ends with ")", where the text enclosed in parentheses is the annotation name and the value is an instance of that annotation.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +| /&lt;relativeUri&gt;? | A nested resource, which is identified as any node whose name begins with a slash (`/`), and SHALL therefore be treated as a relative URI.
```suggestion
| /&lt;relativeUri&gt;? | A nested resource is any node whose name begins with a slash (`/`). This resource SHALL therefore be treated as a relative URI.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +Although a URI parameter MAY be explicitly specified as optional, it SHOULD be required when surrounded directly by slashes (`/`). In this case, the URI parameter constitutes a complete URI path frag
```suggestion
Although a URI parameter MAY be explicitly specified as optional, it SHOULD be required when surrounded directly by slashes (`/`). In this case, the URI parameter constitutes a complete URI path fragment, for example `.../{objectId}/...`. It usually makes no sense to allow a URI to contain adjacent slashes, enclosing no characters, for example, `...//...`. Therefore, a URI parameter SHOULD be specified as optional only when it appears adjacent to other text. For example, `/people/~{fieldSelectors}` indicates that URI parameter `{fieldSelectors}` can be blank, and therefore optional, which implies that `/people/~` is a valid relative URI.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +RESTful API methods are operations that are performed on a resource. The OPTIONAL properties **get**, **patch**, **put**, **post**, **delete**, **head**, and **options** of a resource define its meth
```suggestion
RESTful API methods are operations that are performed on a resource. The OPTIONAL properties **get**, **patch**, **put**, **post**, **delete**, **head**, and **options** of a resource define its methods. These properties correspond to the HTTP methods defined in the HTTP version 1.1 specification [RFC2616](https://www.ietf.org/rfc/rfc2616.txt) and its extension, [RFC5789](https://tools.ietf.org/html/rfc5789). The value of these method properties MUST be a map with the following key-value pairs:
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +An API's methods MAY support or require various HTTP headers. The OPTIONAL **headers** node MAY be used to explicitly specify those headers. The value of the headers node MUST be a map, specifically
RE ", as is the value of the properties object of a type declaration. " Grammatically unclear what it refers to, though I assume it means that the value is also a properties declaration map. People who speak English as a second language could conceivably find it unclear.

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +An API method MAY support or require a query string in the URL on which the method is invoked. The query string in a URL MUST follow [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) as the part of the
```suggestion
An API method MAY support or require a query string in the URL on which the method is invoked. The query string in a URL MUST follow [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) specifications for the part of the URL following the question mark separator (`?`) and preceding any fragment (`#`) separator. The query string MAY be specified either by the OPTIONAL **queryString** node or by the OPTIONAL **queryParameters** node. The queryString and queryParameters nodes SHALL BE mutually exclusive: processors MUST NOT allow both to be specified, explicitly or implicitly, on the same method of the same resource.
```

2020-12-17 21:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +A trait, like a method, can provide method-level nodes such as description, headers, query string parameters, and responses. Methods that use one or more traits inherit nodes of those traits. A resou
```suggestion
A trait, like a method, can provide method-level nodes such as a description, headers, query string parameters, and responses. Methods that use one or more traits inherit nodes of those traits. A resource and resource type can also use, and thus inherit from, one or more traits, which then apply to all methods of the resource and resource type. Traits are related to methods through a mixin pattern.
```

2020-12-24 04:27 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +Any JSON number, positive or negative multiple of 1. The integer type inherits its facets from the [number type](#number).
The former. Thanks!

2020-12-24 04:31 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +A XML schema, or JSON schema, MUST NOT be used where the media type does not allow XML-formatted data, or JSON-formatted data, respectively. XML and JSON schemas are also forbidden in any declaration
Thanks! I learnt something today :)

2020-12-24 04:34 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +User-defined facets by definition are not built into this RAML specification, and hence their semantic MAY not be understood by all RAML processors. Consequently, a RAML processor may or may not choo
You're right.

2020-12-24 04:36 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +If a sub-type inherits properties having the same name from at least two of its parent types, the sub-type SHALL keep all restrictions applied to those properties with two exceptions: 1) a "pattern"
It should, yes.

2020-12-24 04:44 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +An API's methods MAY support or require various HTTP headers. The OPTIONAL **headers** node MAY be used to explicitly specify those headers. The value of the headers node MUST be a map, specifically
Agreed. Maybe something like: ", similarly to the properties node."

2020-12-24 04:46 UTC, jstoiko commented on versions/raml-10/raml-10.md
> +An API method MAY support or require a query string in the URL on which the method is invoked. The query string in a URL MUST follow [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) as the part of the
I think it should be "the RFC3986 specification" (singular) as we normally refer to a RFC as a specification and RFC3986 is a single RFC.

2020-12-29 00:37 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +An API method MAY support or require a query string in the URL on which the method is invoked. The query string in a URL MUST follow [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) as the part of the
ah, ok. I edited the suggestion.

2020-12-29 00:44 UTC, dukesphere reviewed
add suggested modification

2020-12-29 00:44 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +An API's methods MAY support or require various HTTP headers. The OPTIONAL **headers** node MAY be used to explicitly specify those headers. The value of the headers node MUST be a map, specifically
```suggestion
An API's methods MAY support or require various HTTP headers. The OPTIONAL **headers** node MAY be used to explicitly specify those headers. Like the value of the properties node, the value of the headers node MUST be a map, specifically a [properties declaration](#property-declarations). Each property in this declaration object is a header **declaration**. Each property name specifies an allowed header name. Each property value specifies the header value type as a type name or an inline type declaration.
```

2020-12-29 00:51 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +An API method MAY support or require a query string in the URL on which the method is invoked. The query string in a URL MUST follow [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) as the part of the
revised via a suggestion below. "Like the value of the properties node, the value of the headers node MUST be a map, specifically a [properties declaration](#property-declarations)."

2020-12-29 17:55 UTC, dukesphere approved these changes

2020-12-29 17:58 UTC, dukesphere reviewed
minor suggestion

2020-12-29 17:58 UTC, dukesphere commented on versions/raml-10/raml-10.md
> +If a sub-type inherits properties having the same name from at least two of its parent types, the sub-type SHALL keep all restrictions applied to those properties with two exceptions: 1) a "pattern"
```suggestion
If a sub-type inherits properties having the same name from at least two of its parent types, the sub-type SHALL keep all restrictions applied to those properties with two exceptions: 1) a `pattern` facet when a parent type already declares a `pattern` facet 2) a user-defined facet when another user-defined facet has the same value. In these cases, an invalid type declaration occurs.
```

2020-12-30 01:04 UTC, dukesphere approved these changes

2021-04-09 22:39 UTC, merged